### ISSUE TITLE
Implementing Medusa Paystack to the Storefront

### ISSUE THREAD

**Issue by jamalnugolab** [a11rew/medusa-payment-paystack#138]
I'm working on integrating the Paystack payment gateway with my Medusa storefront, but I'm having trouble figuring it out 

How do you handle the payment flow and redirects between Medusa and Paystack during checkout?
Are there any up-to-date code examples or tutorials available for this integration?

Any guidance or advice would be greatly appreciated! Let me know if you need any additional context or details from me.

**Comment by a11rew** [comment]
Hi. We have examples of integrations in the [examples directory](https://github.com/a11rew/medusa-payment-paystack/tree/main/examples) in this repo. The storefront example in there is the [Medusa Next.js starter](https://github.com/medusajs/nextjs-starter-medusa) adapted for this integration. 

You could find all the places where the starter was modified by doing a "paystack" code search in the storefront directory. [Example here ](https://github.com/search?q=repo%3Aa11rew%2Fmedusa-payment-paystack+path%3A%2F%5Eexamples%5C%2Fstorefront%5C%2F%2F+paystack&type=code)
