### ISSUE TITLE
Replace out of date `paystack-api` package

### ISSUE THREAD

**Issue by a11rew** [a11rew/medusa-payment-paystack#21]
We currently depend on version `^2.0.6` of the [`paystack-api` package](https://github.com/pariola/paystack), it's used internally for making calls to the Paystack API.

The package hasn't been updated in 2 years though and depends on a number of deprecated packages, triggering NPM deprecated package warnings when this plugin is installed.

![Screenshot 2023-08-06 at 3 26 39 PM](https://github.com/a11rew/medusa-payment-paystack/assets/87580113/021fd13c-5c6c-49a5-aa63-8bedf4dd0cda)

We need to either replace this package with another maintained wrapper of the Paystack API or handle making the calls manually.

**Comment by agamswaroop619** [comment]
Can you please guide mw through this issue. I am new to open source and would like to contribute

**Comment by a11rew** [comment]
Hi @agamswaroop619, welcome!

This would involve replacing all calls made with the current Paystack SDK in this file https://github.com/a11rew/medusa-payment-paystack/blob/main/packages/plugin/src/services/paystack-provider.js. It could be with another Paystack library or manually making the calls to the API. 
This wrapper maintained by the Paystack team would be a good choice https://github.com/PaystackOSS/paystack-node 

You could use this demo repo https://github.com/a11rew/medusa-paystack-demo along with the [linking instructions here](https://docs.medusajs.com/development/plugins/create#test-your-plugin) to test your changes locally.  

Happy to answer any other questions you have

**Comment by agamswaroop619** [comment]
Thanks @a11rew for such quick response! 

Sure, I will first try to locally run the demo repo tonight and get back to you for any further enquires if any.

**Comment by a11rew** [comment]
Ah that would be a blocker @agamswaroop619. A Paystack account is be needed to get setup locally and verify changes work as expected.

**Comment by agamswaroop619** [comment]
Sorry for troubling you, @a11rew.
If anything else comes up that I can help please feel free to ask me!
I will try my best to support in any way or form as I can!

**Comment by a11rew** [comment]
Sure thing, definitely not a bother @agamswaroop619
