### ISSUE TITLE
Paystack payment not initiating

### ISSUE THREAD

**Issue by JaeKralj** [a11rew/medusa-payment-paystack#51]
the error is "'secret_key' not a valid key=value pair (missing equal-sign) in Authorization header: <secret_key>"

**Comment by a11rew** [comment]
@JaeKralj it would seem your secret_key is not set correctly in your Medusa config. 

Confirm this is set correctly, provide more context on your issue if it persists: Medusa version, `medusa-payment-paystack` version, what action you were taking specifically when this happened

**Comment by JaeKralj** [comment]
this is how I have set it up

created env variable for secret key
![image](https://github.com/a11rew/medusa-payment-paystack/assets/70724119/97ae5230-2845-425b-84ae-110bae18f525)

then I configured medusa.config.js like so
![image](https://github.com/a11rew/medusa-payment-paystack/assets/70724119/4063b8cf-7350-493d-bf9c-9299f2918b6a)

**Comment by JaeKralj** [comment]
medsajs/medusa v1.16.0,
the issue occurs when I click the paystack option, more precisely when initatePayment is called

**Comment by a11rew** [comment]
I cannot reproduce this on my Medusa store instance running v1.1.2 of the package. Are you able to reliably reproduce it? Do you get an indication the error is returned from Paystack or occurs before the initiate payment request is sent to Paystack to begin with?

Please share the entire error: error message and stack trace

**Comment by JaeKralj** [comment]
This is reproduced reliably, I'd attempt to recreate the Backend again, and build from scratch.

The error is from paystack, I copied the code of the plugin to really debug the error, the error is from paystack.

The error I get from the plugin is cannot read property of undefined reading reference (data.reference is returned in the initiatePayment function)

**Comment by a11rew** [comment]
Ahh, from Paystack. It'd be really helpful to know when/why this happens, so we could add a case to handle this or provide a more helpful feedback. Looking forward to hearing what you find @JaeKralj

**Comment by JaeKralj** [comment]
> Ahh, from Paystack. It'd be really helpful to know when/why this happens, so we could add a case to handle this or provide a more helpful feedback. Looking forward to hearing what you find @JaeKralj 

I copied the code, and used axios instead of the http module, it lead to decrease in lines of code, improved readability and most importantly solved the issue for me, can I submit a PR with this little tweak?

**Comment by a11rew** [comment]
Yes @JaeKralj, submit the PR.
